// maps keycode to each matrix position, this also will store each layer map once we make multiple layers
#include "key_map.h"
#include "key_codes.h"

int BASE_LAYOUT[NUM_ROWS][NUM_COLUMNS] = {
    {KEY_ESC, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0, KEY_MINUS, KEY_EQUAL, KEY_BACKSPACE, KEY_DELETE},
    {KEY_TAB, KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_Y, KEY_U, KEY_I, KEY_O, KEY_P, KEY_LEFTBRACE, KEY_RIGHTBRACE, KEY_BACKSLASH, KEY_PAGEUP},
    {KEY_CAPSLOCK, KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_H, KEY_J, KEY_K, KEY_L, KEY_SEMICOLON, KEY_APOSTROPHE, KEY_NONE, KEY_ENTER, KEY_PAGEDOWN},
    {KEY_MOD_LSHIFT, KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M, KEY_COMMA, KEY_DOT, KEY_SLASH, KEY_NONE, KEY_MOD_RSHIFT, KEY_UP, KEY_END},
	{KEY_MOD_LCTRL, KEY_MOD_LMETA, KEY_MOD_LALT, KEY_NONE, KEY_NONE, KEY_NONE, KEY_SPACE, KEY_NONE, KEY_NONE, KEY_MOD_RALT, KEY_MOD_FN, KEY_MOD_RCTRL, KEY_LEFT, KEY_DOWN, KEY_RIGHT}
};
